### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rzr**
Reformat to markdown..

Any plans for future.

### CODE REVIEW

**Comment by rzr** [comment]
Is this project still active ? if not is there a living fork or similar project ?

**Comment by joanbarros** [comment]
I don't know if it's still active but I'm interested. If the original maintainer will not continue it would be nice to know so we can look for a fork or create one.

I have a couple of projects I would like to use this for.

**Comment by sampoz** [comment]
Hi guys! 

I have been longing for a proper, Open Source BMS for a while, and I ran in to a cool build of electric longboard, that seems to use a DIY BMS. Maybe it could be branched of to seperate project? Here is a [link to the project](https://github.com/lolomolo/LongboardMarkII) and a picture of a BMS node that caught my attention: A picture of the BMS node in question

**Comment by Teslafly** [comment]
This project is probably halfway dead. I have not had time to work on it with various other projects and college, but I am halfway into building an ebike, so the current iteration will probably be finished for that reason.

What really needs to be done is to change out to a different bms ic. the one i used in this project is tending towards obsolete, and there are much better ones available now like the BQ76940. (not daisy chainable, but isolated with a mux is still less complex / cheaper.)

**Pull request merged**
